### ISSUE TITLE
Unclear naming between manuscript, code and GEO data.

### ISSUE THREAD

**Issue by talban14** [zhangzlab/covid_balf#1]
Hi, it's unclear to me which sample is which with your GEO names being (BALF, C141), but then the samples naming in the patient demographics table and in the manuscript and in teh code being HC1, M1, M2 ect and it appear that you've read in files with these names alread changed or organized in the code here.  

Can you please provide a key to deciphering which sample is which in correspondance with your manuscript?

**Comment by zhangzlab** [comment]
Please refer to meta.txt, sorry for the inconvenience.

**Comment by zhangzlab** [comment]
Please refer to meta.txt, sorry for the inconvenience.
