### ISSUE TITLE
Control Sex effects during scaling and DEG analysis

### ISSUE THREAD

**Issue by ghost** [zhangzlab/covid_balf#10]
Hi,

Thank you for sharing all the resources and codes.
Have you noticed or tried to regress out gender effects during scaling or DEG analysis?

**Comment by zhangzlab** [comment]
No, we didn't control sex effects in the analysis. You can try whether gender effect has much influence on the final results.

**Comment by ghost** [comment]
Cool. Thank you!
I had a problem where Xist and other sex-related genes alwalys came up when I did DEGs analysis. I'm trying to figure out what is the best way to regress out sex effects in Seurat package.
