### ISSUE TITLE
Why no upper limit on nCount_RNA?

### ISSUE THREAD

**Issue by uberholzer** [zhangzlab/covid_balf#12]
Hi,

I am curious about why your preprocessing pipeline defines a lower limit for UMI count (nCount_RNA) of 1,000 but does not define an upper limit. For example, this tutorial suggests an upper UMI count limit of 20,000: https://ucdavis-bioinformatics-training.github.io/2019-single-cell-RNA-sequencing-Workshop-UCD_UCSF/scrnaseq_analysis/scRNA_Workshop-PART2.html

Looking at the QC metrics I can see that many cells in your dataset have UMI counts largely exceeding 20,000. Is there a reason your team did not define an upper limit?

Thanks for your help.

**Comment by zhangzlab** [comment]
The main reason for setting UMI upper limit is removing multiplets. But it may be hard since some highly proliferative cells have high UMIs. So we keep the cells with high UMIs and remove the potential doublets after clustering.
