### ISSUE TITLE
why "first generate data and scale data in RNA assay"?

### ISSUE THREAD

**Issue by yingyonghui** [zhangzlab/covid_balf#13]
Hi all,
Thanks for your public data and code!
I just have a question about the code which is annotated with "first generate data and scale data in RNA assay". 
`###first generate data and scale data in RNA assay
DefaultAssay(nCoV.integrated) <- "RNA"
nCoV.integrated[['percent.mito']] <- PercentageFeatureSet(nCoV.integrated, pattern = "^MT-")
nCoV.integrated <- NormalizeData(object = nCoV.integrated, normalization.method = "LogNormalize", scale.factor = 1e4)
nCoV.integrated <- FindVariableFeatures(object = nCoV.integrated, selection.method = "vst", nfeatures = 2000,verbose = FALSE)
nCoV.integrated <- ScaleData(nCoV.integrated, verbose = FALSE, vars.to.regress = c("nCount_RNA", "percent.mito"))
`
As far as I understand, this block of code does NormalizeData, FindVariableFeatures, and ScaleData on the "RNA" assay.
I'm just wondering the meaning of this process. Since NormalizeData has been done for each dataset before integration, I think there's no need to normalize again. For  FindVariableFeatures and ScaleData, I think they are also unnecessary since the following procedures are based on the "integrated" assay.
Apologize if I've missed some important point!

Best,
Yingyong

**Comment by zhangzlab** [comment]
Yes, you are right. For each assay, NormalizeData only needs to run once, you can remove the code of NormalizeData, etc. before integration. And running ScaleData or not is up to you. If you don't need the scaled data in RNA assay for visualization, you can comment out the code.
