### ISSUE TITLE
How can I find _bp.txt?

### ISSUE THREAD

**Issue by chenxofhit** [zhangzlab/covid_balf#16]
When I review the codes, I find that the file named "_bp.txt" is missing,
the corresponding line is: https://github.com/zhangzlab/covid_balf/blob/master/NKT.R#L379 .

Could you help me with how can I get the file?

**Comment by polojacky** [comment]
This file is generated from line 362 or line 369. You can replace it with _bp_severe or _bp_mild as you wish.

**Comment by zhangzlab** [comment]
This file is generated from line 362 or line 369. You can replace it with _bp_severe or _bp_mild as you wish.

**Comment by chenxofhit** [comment]
Thanks for your answer.
