### ISSUE TITLE
SARS-CoV-2 genes in count matrix

### ISSUE THREAD

**Issue by MarcElosua** [zhangzlab/covid_balf#17]
Hello,

Thank you very much for making the data used for this study so easily accessible!
I downloaded the file `nCoV.rds` from the link in the README and I am trying to identify which cells have SARS-CoV-2 transcripts but cannot seem to find the correct gene name. In the methods of the paper, it says that you mapped the reads to an integrated human GRCh38 and SARS-CoV-2 genome. Could you point me in the direction of how to get the transcript level information of SARS-CoV-2 genes for each cell?

Thanks a lot!
Marc

**Comment by zhangzlab** [comment]
Hi Marc,

nCoV is used to denote the SARS-CoV-2 genome, we didn't map the sequence to individual genes of SARS-CoV-2.
