### ISSUE TITLE
10x chemistry of samples

### ISSUE THREAD

**Issue by mxposed** [zhangzlab/covid_balf#23]
Hello,

Could you please confirm which chemistry was used for which samples in the study?

In [the methods](https://www.nature.com/articles/s41591-020-0901-9#Sec2) you say
> Single-cell capturing and downstream library constructions were performed using Chromium Single Cell 3g Reagent kits v.2 (10x Genomics; PN-120237, PN-120236 and PN-120262) for HC1 and HC2, kit v.3 (10x Genomics; PN-1000075, PN-1000073 and PN-120262) for HC3 and Chromium Single Cell V(D)J Reagent kits (10x Genomics; PN-1000006, PN-1000014, PN-1000020, PN-1000005) for all patients with COVID-19

which I interpret like this:
2 healthy control samples were prepared with 10x 3' V2
1 healthy control sample was prepared with 10x 3' V3
all COVID-19 samples were prepare with 10x 5' 

However, on GEO this information is lacking, and all samples are reported as 10x 5': https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4475048

I would be very grateful for clarification and maybe updated materials! Thank you

**Comment by zhangzlab** [comment]
You are right. The description in GEO is not accurate, and please follow the information provided in the original paper. Will revise the description in GEO later, thanks!

**Comment by mxposed** [comment]
Thank you for the quick reply!
