### ISSUE TITLE
Why ScaleData twice?

### ISSUE THREAD

**Issue by uberholzer** [zhangzlab/covid_balf#3]
Hi,
I am wondering why you use the ScaleData function on the RNA Assay twice in the seurat_integration script. The first time, you have:
`nCoV.integrated <- ScaleData(nCoV.integrated, verbose = FALSE, vars.to.regress = c("nCount_RNA", "percent.mito"))` right before visualization and clustering.

The second time, you have: 
`var.genes = c(nCoV.integrated@assays$RNA@var.features,top30$gene,markers)
nCoV.integrated <- ScaleData(nCoV.integrated, verbose = FALSE, vars.to.regress = c("nCount_RNA", "percent.mito"),features = var.genes)` right before plotting the split UMAPs.

What is the reason for scaling the data twice? Does the second command overwrite the scale.data slot?

Thanks!

**Comment by zhangzlab** [comment]
Yes, by default ScaleData only scale the HVGs calculated in FindVariableFeatures, which missed some differential expressed genes in FindAllMarkers. So for visualization purposes (e.g., DoHeatmap), we rerun ScaleData to include these missed genes.

**Comment by uberholzer** [comment]
I see. Thanks for the prompt response!
