### ISSUE TITLE
balf_1.txt

### ISSUE THREAD

**Issue by maximilianh** [zhangzlab/covid_balf#7]
Hi, we're trying to run your seurat_integration script but it requires a file balf_1.txt which is not in the Github repository. Could you add this file?

thanks!

**Comment by polojacky** [comment]
Please refer to meta.txt.

**Comment by maximilianh** [comment]
many thanks for the quick reply! 

Another question: we're trying to run your analysis script, but while removing all the obstacles and fighting against R packages, I was wondering: couldn't you provide the final Seurat.rds file with the raw and integrated dataset? That may be easier for most users, like me, to get the full dataset, rather than us having to download .h5, R and .txt files. I imagine you have this Seurat object on your disk, possibly as a data file already... you could copy a dropbox or similar link into the README file and possibly this would save a lot of questions in Github...?

**Comment by zhangzlab** [comment]
Yes, that's a good idea. I'll try to find an option since the file is too big to be included in Github repo. Dropbox is not available, maybe OneDrive.

**Comment by maximilianh** [comment]
We could also host it for you. Email mspeir@ucsc.edu and/or me, you can
upload the file via an sftp account here that we create for you and we can
provide the file through our servers under a normal URL instead of a free
cloud something account. We are building an interactive browser for your
data and can attach any supplemental files there. Also other big files you
may have (images, etc)

**Comment by maximilianh** [comment]
Hi!

Yes, happy to host it. Let us know, we can set up sftp for you to upload
the data and we can host your dataset visualization through our site.

----

Matthew Speir

UCSC Cell Browser, Quality Assurance and Data Wrangler

Human Cell Atlas, User Experience Researcher

UCSC Genome Browser, User Support

UC Santa Cruz Genomics Institute <http://genomics.ucsc.edu/>

Revealing life’s code.

**Comment by zhangzlab** [comment]
Please send the account info to jack.liu9@outlook.com.

**Comment by zhangzlab** [comment]
Please send the account info to jack.liu9@outlook.com.
