### ISSUE TITLE
doublet rate in samples

### ISSUE THREAD

**Issue by tilofrei** [zhangzlab/covid_balf#9]
Hi,

Thank you for providing this amazing dataset. I try to estimate the doublet/multiplet rate of your samples which is based on the number of cells loaded into the 10x chromium device.

Do you know the number of cells loaded or alternatively if each sample was run in exactly 1 well?

Best
Tilo

**Comment by zhangzlab** [comment]
Yes, before loading into 10x, Trypan Blue was used to check the viability, and cell counting was performed. But only a fraction of cells was loaded into 10x finally based on the quality of cells, so we don't know the exact number of cells loaded. You can estimate the doublet rate according to 10x empirical value, e.g., 7.6% in 10,000 recovered cells. But I think it varies from sample to sample.

**Comment by tilofrei** [comment]
Thanks, that works!
